#!/bin/sh

#export IFORTLIB="/opt/intel/lib:/opt/intel/mkl/lib" 
#export DYLD_LIBRARY_PATH="${IFORTLIB}"

# Estimating channel parameters (depth, width) by empirical equations of annual discharge
# Please execute this shell script in $CaMa-Flood/map/$MAPNAME directory
# % cd $MAPNAME
# % ../s01-channel_params.sh

################
# input runoff forcings

echo "=== get_rivinfo ==="

./get_rivinfo latlon 13.525	105.942	

echo "******"
echo "Stung Toreng XY : 160, 215"

echo "=== get_upbasin ==="
echo "calculate upstream basin of Stung Toreng"

./get_upbasin 160 215 st_upst.bin

mv st_upst.bin ..

echo "==================="
echo ""
echo "upstream basin of Stung Toreng saved as st_upst.bin"
echo "then execute s01-*.sh to generate river parameters. Also, a river netwpork map downstream of ST is generated by calc_outclm.F90 (modified for LonleSap simulaton)"
