SUBROUTINE HEATLINK_CAPTURE_RIVER_WATER_ADVECTION_STATE
USE HEATLINK_RIVER_MOD, ONLY: CAPTURE_RIVER_WATER_ADVECTION_STATE
IMPLICIT NONE

CALL CAPTURE_RIVER_WATER_ADVECTION_STATE
END SUBROUTINE HEATLINK_CAPTURE_RIVER_WATER_ADVECTION_STATE


SUBROUTINE HEATLINK_ADVANCE_RIVER_WATER_ADVECTION(DT_SECONDS)
USE PARKIND1, ONLY: JPRB
USE HEATLINK_RIVER_MOD, ONLY: ADVANCE_RIVER_WATER_ADVECTION
IMPLICIT NONE
REAL(KIND=JPRB), INTENT(IN) :: DT_SECONDS

CALL ADVANCE_RIVER_WATER_ADVECTION(DT_SECONDS)
END SUBROUTINE HEATLINK_ADVANCE_RIVER_WATER_ADVECTION
